Repository freerange/mocha, pull requests merged in 2019-11, with the labels that each got.

#385 Add documentation to explain how Mocha is intended to be used
  README.md
Labels: documentation

#402 Do not include method definer into all objects
  test/method_definer.rb
  test/unit/any_instance_method_test.rb
  test/unit/central_test.rb
  test/unit/expectation_list_test.rb
  test/unit/expectation_test.rb
  test/unit/instance_method_test.rb
  test/unit/object_inspect_test.rb
Labels: quality

#417 Fix test failures on Mac OSX Catalina
  lib/mocha/macos_version.rb
  test/unit/mock_test.rb
Labels: compatibility, quality

#418 Put deprecations into effect
  lib/mocha/api.rb
  lib/mocha/integration.rb
  lib/mocha/mini_test.rb
  lib/mocha/mock.rb
  lib/mocha/mockery.rb
  lib/mocha/parameter_matchers/equivalent_uri.rb
  lib/mocha/standalone.rb
  lib/mocha_standalone.rb
  test/acceptance/mock_with_initializer_block_test.rb
  test/unit/mockery_test.rb
  test/unit/parameter_matchers/equivalent_uri_test.rb
Labels: quality

#421 Configuration improvements
  lib/mocha/configuration.rb
  lib/mocha/expectation.rb
  lib/mocha/mockery.rb
  test/acceptance/display_matching_invocations_alongside_expectations_test.rb
  test/acceptance/stubbing_error_backtrace_test.rb
  test/acceptance/stubbing_method_unnecessarily_test.rb
  test/acceptance/stubbing_nil_test.rb
  test/acceptance/stubbing_non_existent_any_instance_method_test.rb
  test/acceptance/stubbing_non_existent_class_method_test.rb
  test/acceptance/stubbing_non_existent_instance_method_test.rb
  test/acceptance/stubbing_non_public_any_instance_method_test.rb
  test/acceptance/stubbing_non_public_class_method_test.rb
  test/acceptance/stubbing_non_public_instance_method_test.rb
  test/acceptance/stubbing_on_non_mock_object_test.rb
  test/unit/configuration_test.rb
Labels: feature-request, quality

#428 Hide ClassMethods#method_visibility & #method_exists? methods to avoid clash with Rails
  lib/mocha/class_methods.rb
  lib/mocha/mockery.rb
  lib/mocha/stubbed_method.rb
Labels: compatibility, quality
