Repository freerange/mocha, pull requests merged in 2019-10, with the labels that each got.

#373 Pin minitest to v5.11.3 for Ruby v1.8.7 to fix build
  .travis.yml
  gemfiles/Gemfile.minitest.5.11.3
Labels: compatibility, quality

#374 Upgrade JRuby to v9.2.8.0 in Travis CI builds
  .travis.yml
Labels: compatibility

#376 Only run rubocop for MRI Ruby versions & non-integration test builds
  Rakefile
Labels: quality

#383 More realistic examples for yields and multiple_yields
  lib/mocha/expectation.rb
Labels: documentation

#384 Improve documentation for responds_like{,_instance_of}
  lib/mocha/api.rb
  lib/mocha/mock.rb
Labels: documentation

#386 Document MOCHA_OPTIONS in README
  README.md
Labels: documentation

#392 Don't over-write definition of singleton_class
  lib/mocha/class_methods.rb
  lib/mocha/mockery.rb
  lib/mocha/object_methods.rb
Labels: quality
